runtime: python314
entrypoint: gunicorn -w 4 -b :$PORT backend.app:app

env: standard
instances: 1

env_variables:
  PYTHONUNBUFFERED: "1"

automatic_scaling:
  min_instances: 1
  max_instances: 10

handlers:
  - url: /.*
    script: auto
